$schema: "../../../build/generated/ksp/main/resources/META-INF/config-schema.yaml"
slack:
  server:
    enabled: true
  channels:
    - id: C0B783F5CLW

redis:
  url: redis://redis:6379

opencode:
  server:
    enabled: true
    env:
      custom:
        OPENCODE_CONFIG_DIR: /var/opencode-agents/config
        OPENCODE_CONFIG: /var/opencode-agents/config/opencode.json
  configSync:
    enabled: false
    targetDir: "/var/opencode-agents/config"
    ssh:
      sshDir: "/var/opencode-agents/.ssh"
      privateKeyPath: "/var/opencode-agents/.ssh/github"
