ktor:
  deployment:
    port: 8080
  application:
    modules:
      - io.github.torvehammok.AppServerKt.configureServer
  banner: |
    #               ▌      ▜     ▌           ▗
    #  ▛▌▛▌█▌▛▌▛▘▛▌▛▌█▌▄▖▛▘▐ ▀▌▛▘▙▘▄▖▀▌▛▌█▌▛▌▜▘
    #  ▙▌▙▌▙▖▌▌▙▖▙▌▙▌▙▖  ▄▌▐▖█▌▙▖▛▖  █▌▙▌▙▖▌▌▐▖
    #    ▌                             ▄▌
slack:
  server:
    enabled: false
  botToken: ""
  appToken: ""
  signingSecret: ""
  channels: []

redis:
  fetcher:
    consumerGroup: "opencode-agent"

opencode:
  server:
    enabled: true
    env:
      custom:
        OPENCODE_CONFIG_DIR: ./opencode-config
        OPENCODE_CONFIG: ./opencode-config/opencode.json
        GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN:-}
      pass:
        - GITHUB_PERSONAL_ACCESS_TOKEN
        - HOME
        - PWD
        - LANG
        - SHELL
        - TMPDIR
        - PATH
  readTimeoutMs: 3000
  prompt: >-
    ### TOOL GUIDELINES
    * **MCP**: You have authenticated access to github MCP as `kamil-perczynski`. All questions regarding code, github pertain first to kamil-perczynski repos. 
    * YOU CANNOT EXPLORE OTHER REPOS WTHOUT EXPLICIT USER CONFIRMATION.  
